#!/bin/bash
DEFAULT_BUILD_CONFIGURATION="debug"
TOOL_NAME="JPEGRegressionTests"
DEFAULT_BUILD_FLAGS=""

usage()
{
    echo "usage: utils/$TOOL_NAME [OPTION...]
  -c, --configuration       swift build configuration mode, default '$DEFAULT_BUILD_CONFIGURATION'
  -b, --build-flags         swift build additional command flags, default '$DEFAULT_BUILD_FLAGS'
  -u, --update              remove and regenerate golden outputs (tests will fail)"
}

error()
{
    echo $1
    exit 1
}

check()
{
    message=$1
    shift
    echo $@
    "$@" || error "$message"
}

build_configuration=$DEFAULT_BUILD_CONFIGURATION
build_flags=$DEFAULT_BUILD_FLAGS

while [ "$1" != "" ] ; do
    case $1 in
    -c | --configuration )
        shift
        build_configuration=$1
        ;;
    -b | --build-flags )
        shift
        build_flags=$1
        ;;
    -u | --update )
        shift
        gold=(tests/regression/gold/*.jpg.ycc)
        echo "the following ${#gold[@]} golden outputs will be removed and regenerated:"
        for file in ${gold[@]} ; do
            echo "    $file"
        done
        echo "note: regression tests will fail. regression tests will pass on the next run."
        echo -n "press enter to confirm>"
        read confirmation
        rm ${gold[@]}
        ;;
    * )
        usage
        exit 1
    esac
    shift
done

check   "error: swift build failed" \
        swift build -c $build_configuration --product $TOOL_NAME $build_flags

binaries=".build/$build_configuration"
if ! [ -f $binaries/$TOOL_NAME ]; then
    error "error: missing $TOOL_NAME tool"
fi

check   "error: test failures" \
        $binaries/$TOOL_NAME
