#!/bin/bash
TOOL_NAME="unit-test"
error()
{
    echo $1 
    exit 1
}

check()
{
    message=$1
    shift 
    echo $@
    "$@" || error "$message"
}

check   "error: test failures" \
        swift run -c debug $TOOL_NAME 
