name: tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            - name: Install Swift
              uses: tayloraswift/swift-install-action@master
              with:
                  swift-prefix: "swift-6.0.3-release/ubuntu2404/swift-6.0.3-RELEASE"
                  swift-id: "swift-6.0.3-RELEASE-ubuntu24.04"

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install imagemagick
              run: sudo apt install -y imagemagick

            - name: Run tests
              run: Scripts/TestAll

    linux-musl:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            - name: Install Swift
              uses: tayloraswift/swift-install-action@master
              with:
                  swift-prefix: "swift-6.0.3-release/ubuntu2404/swift-6.0.3-RELEASE"
                  swift-id: "swift-6.0.3-RELEASE-ubuntu24.04"

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install imagemagick
              run: sudo apt install -y imagemagick

            - name: Install linux SDK
              run: swift sdk install https://download.swift.org/swift-6.0.3-release/static-sdk/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 67f765e0030e661a7450f7e4877cfe008db4f57f177d5a08a6e26fd661cdd0bd

            - name: Run tests
              run: Scripts/TestAll -b "--swift-sdk x86_64-swift-linux-musl"

    macos:
        runs-on: macos-15
        name: macOS
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install imagemagick
              run: brew install imagemagick

            - name: Run tests
              run: Scripts/TestAll
